VAGRANT_API_VERSION = "2"
# used https://app.vagrantup.com/ubuntu/boxes/focal64

Vagrant.configure(VAGRANT_API_VERSION) do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 443, host: 8443
    config.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("/home/mmbl/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
        echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
        echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
        SHELL
        end
end
