---
- name: Configure webserver whith nginx and tls
  hosts: webservers
  become: True
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        update_cache: yes
        cache_valid_time: 3600

    - name: Create directories for ssl certificates
      file:
        path: /etc/nginx/ssl
        state: directory
        owner: root
        mode: 0600

    - name: Copy TLS key
      copy:
        src: files/nginx.key
        dest: "{{ key_file }}"
        owner: root
        mode: 0600
      notify: Restart nginx

    - name: Copy TLS certificate
      copy:
        src: files/nginx.crt
        dest: "{{ cert_file }}"
      notify: Restart nginx

    - name: Copy nginx config file
      template:
        src: templates/nginx.conf.j2
        dest: "{{ conf_file }}"
        mode: 0644
      notify: Restart nginx

    - name: Enable configuration nginx
      file:
        dest: /etc/nginx/sites-enabled/default
        src: "{{ conf_file }}"
        state: link
      notify: Restart nginx

    - name: Copy index.html
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: 0644
  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
